name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: task_manager_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v3
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Database Setup
        run: |
          cp config/database.yml.example config/database.yml
          RAILS_ENV=test bundle exec rails db:create db:schema:load

      - name: Run Tests
        run: |
          bundle exec rspec
